### ISSUE TITLE
Not scrolling

### ISSUE THREAD

**Issue by michal-pusz** [rheng001/react-native-wheel-scrollview-picker#14]
Checked on Android Device and emulator, when wrapped by **SafeAreaView** and **KeyboardAwareScrollView** picker don't move.
It works perfect on iOS tho

**Comment by ftzi** [comment]
@rheng001 I was converting the original https://github.com/veizz/react-native-picker-scrollview to Functional Components until I found out yours that did exactly the same (apparently @yasemincidem did it and then you improved further). I've been tinkering it and adapting it to my needs and tastes (maybe I will PR it or create a new package, as I did some breaking stuff for older versions and you may not like it).

I was also having the @ick56 issue on some specific cases, and I just solved it:

~Add the `onStartShouldSetResponder={() => true}` prop to the wrapping view,~ or a Pressable wrapping the ScrollView content. Source: https://stackoverflow.com/a/49918614/10247962

Actually, looks like the `onStartShouldSetResponder` will not work if `overflow: 'hidden'` is set on the style, as it's in your lib. The Pressable solution does work with and without it.

**Comment by Dat-Mobile** [comment]
This issue related to nested scrollview
please checkout my pr for solution
https://github.com/rheng001/react-native-wheel-scrollview-picker/pull/16/files
