### ISSUE TITLE
Style Not working   react-native-wheel-scrollview-picker

### ISSUE THREAD

**Issue by ghost** [rheng001/react-native-wheel-scrollview-picker#19]
wrapperBackground,highlightColor,activeItemTextStyle,itemTextStyle that all props are not working why? i am give some style on this picker but  it is not working 

 <ScrollPicker 
          dataSource={['1', '2', '3', '4', '5', '6']}
          selectedIndex={age}
          renderItem={(data, index) => {
            return( <Text style={{color:'orange',fontSize:25}}>{data}</Text>)
            
          }}
          onValueChange={(data, selectedIndex) => {
           
              setAge(data)
          
            console.log("data selected",data)
            
          }}
        
          wrapperHeight={160}
          wrapperWidth={190}
          wrapperColor='#000'
         
          activeItemTextStyle={{
            color: "#FFF",
            fontSize: 25
          }}
          itemTextStyle={{
            color: "#FFF",
            fontSize: 25
          }}
          wrapperBackground={'#FFFFFF'}
          itemHeight={60}
          highlightColor={'#d8d8d8'}
          highlightBorderWidth={2}
          activeItemColor={'#222121'}
          itemColor={'#B4B4B4'}
        />

**Comment by KrushnaNaghate** [comment]
hi, @lalitkumar64  try this, 
ctrl + click on ScrollPicker 
and copy and paste the following code

1)add these lines above this comment
  // TODO: add proper type to `scrollViewComponent` prop //

itemTextStyle?:any;
activeItemTextStyle?:any;

2) add these lines before useeffect function
  const TextStyle = props.itemTextStyle;
  const activeTextStyle = props.activeItemTextStyle

3)replace renderitem function with this

 const renderItem = (
    data: ScrollPickerProps["dataSource"][0],
    index: number
  ) => {
    const isSelected = index === selectedIndex;
    const item = props.renderItem ? (
      props.renderItem(data, index, isSelected)
    ) : (
      <Text
        style={
          isSelected
            ? [{...styles.itemText,...TextStyle , ...styles.itemTextSelected,...activeTextStyle}]
            : {...styles.itemText,...TextStyle }
        }
      >
        {data}
      </Text>
    );

4)add your styles 

  <ScrollPicker
                    dataSource={yearArr}
                    selectedIndex={yearArr.indexOf(this.state.passingYear)}
                    onValueChange={(year, selectedIndex) => {
                      this.setState({
                        passingYear: year.toString(),
                      });
                    }}
                    activeItemTextStyle={{
                      color: this.context.primaryColor,
                      fontWeight: 'bold',
                      fontSize: 17,
                    }}
                    itemTextStyle={{
                      color: this.context.secondaryFontColor,
                      fontSize: 12,
                    }}
                    wrapperHeight={180}
                    wrapperWidth={150}
                    wrapperColor={this.context.surfaceColor}
                    itemHeight={40}
                    highlightColor={this.context.primaryColor}
                    highlightBorderWidth={2}
                  />


**it will work**
