### ISSUE TITLE
Scroll is not working 

### ISSUE THREAD

**Issue by ForamPattha** [rheng001/react-native-wheel-scrollview-picker#21]
I have list of data but still scroll is not working . Items are not scrollable . here I attached my code 
<ScrollPicker
                                dataSource={[`0"`, `1"`, `2"`, `3"`, `4"`, `5"`, `6"`, `7"`, `8"`, `9"`, `10"`, `11"`]}
                                selectedIndex={1}
                                renderItem={(data, index) => {
                                    return (
                                        <Text style={{ color: 'orange', fontSize: 25 }}>{data}
                                          </Text>
                                        )
                                }}
                                onValueChange={(data, selectedIndex) => {
                                    console.log(data, 'ddddd');
                                }}
                                wrapperHeight={180}
                                wrapperWidth={150}
                                wrapperColor='#FFFFFF'
                                itemHeight={60}
                                highlightColor='#d8d8d8'
                                highlightBorderWidth={2}
                                style={{
                                    marginHorizontal: 0,
                                    backgroundColor: colors.White,
                                    width: wp('35'),
                                    height: hp('25')
                                }}
                            />
   can you please help me to out from this issue or I'm missing something .

**Comment by jasonmcaffee** [comment]
I have the same issue on iOS. Going to look for another library.

**Comment by tammytru** [comment]
@jasonmcaffee were you able to find another one or get this to work?

**Comment by jasonmcaffee** [comment]
No, sorry, I ended up just using a dropdown

**Comment by netojose** [comment]
I got the same error here. Switching to https://www.npmjs.com/package/react-native-wheel-pick instead

**Comment by netojose** [comment]
Almost 2 years later, the issue still happens, I got the same error here.  😞
