### ISSUE TITLE
SelectedIndex is not working

### ISSUE THREAD

**Issue by RonakBansal321** [rheng001/react-native-wheel-scrollview-picker#25]
I'm setting a number in setInchI using useEffect and passing InchI to selectedIndex on scrollPicker as below but its not working and if I pass a static number it is working fine.
  useEffect(() => {
      inchData().map((i, inx) => {
        if (i.value.toString() == heightin) {
          setInchI(inx);
          let selItem = inchData()[inx];
          setInch({
            name: selItem.name,
            value: selItem.value,
          });
        }
      });
    }
  }, []);

      <ScrollPicker
            dataSource={inchData().map((item) => item.name)}
            selectedIndex={inchI}
            onValueChange={(data, selectedIndex) => {
              handleChangeInch(selectedIndex);
            }}
            itemTextStyle={{ color: "#6359a6", fontSize: 25 }}
            activeItemTextStyle={{ color: "#6359a6", fontSize: 30 }}
            wrapperHeight={200}
            wrapperBackground="#FFFFFF"
            itemHeight={50}
            highlightColor="#d8d8d8"
            highlightBorderWidth={2}
          />
          
          please suggest a quick reply. Thanks in advance

**Comment by rheng001** [comment]
Hi @RonakBansal321 

Can you provide more code and context?

**Comment by RonakBansal321** [comment]
> Hi @RonakBansal321
> 
> Can you provide more code and context?

I have used useeffect through which I'm assigning the required data to useState . setInchI is the value of index which is set at useEffect when component loads but selectedIndex is not accepting the number . After that I have passed the data number from the previous page now its working fine after that. Thanks for your reply.
