### ISSUE TITLE
Failed prop type: Invalid prop `highlightWidth` of type `string`

### ISSUE THREAD

**Issue by RobinBobin** [rheng001/react-native-wheel-scrollview-picker#3]
Hi!

I installed version 1.0.2 of your package and I get this error in the console:

Warning: Failed prop type: Invalid prop `highlightWidth` of type `string` supplied to `ScrollPicker`, expected `number`.

Code snippet:

```
<ScrollPicker
      dataSource={["1", "2", "3", "4", "5", "6"]}
      selectedIndex={1}
      renderItem={data => <Text>{data}</Text>}
      wrapperHeight={180}
      wrapperWidth={100}
      wrapperBackground={"#FFFFFF"}
      highlightBorderWidth={1}
/>
```

I can comment out the line `highlightWidth: PropTypes.number,` but I doubt it's a good solution.

**Comment by rheng001** [comment]
Hi @RobinBobin,

Thanks for pointing that out, I pushed a new version fixing the issue. Please update to the new version and let me know!

**Comment by RobinBobin** [comment]
Thanks a lot.

Sorry, I won't be able to check, as I moved to `@gregfrench/react-native-wheel-picker`. I needed 3 pickers in a row and I couldn't get it working with your component.
