### ISSUE TITLE
Type safety & converting code to use functional components

### ISSUE THREAD

**Issue by TGlide** [rheng001/react-native-wheel-scrollview-picker#5]
I've had some issues with this repo, which caused some crashing bugs on my app. Venturing into the code, I found that a lot could be fixed by switching to typescript. Added to that, switching to functional type components would greatly improve code maintainability and keep it more relevant. 

I've made a local component in typescript that does just that, but before I submit a PR, I'd like to know if this is something that would be welcome in this repo.

**Comment by rheng001** [comment]
Hey @TGlide!

I think that'll be a great addition to the library. It's something I've been meaning to do but haven't had the time to, so that would be very appreciated.

Go ahead and submit a PR for it.

**Comment by rheng001** [comment]
PR Merged and library updated. Thank you!
